### ISSUE TITLE
Ability to hide window's title

### ISSUE THREAD

**Issue by emvaized** [Zren/material-decoration#33]
First of all, thanks for such a great project!
It improves system's usability a lot, while looking truly awesome.

I have a small feature request however - would it be possible to add in future builds option to completely hide window's title? 
I feel like I've never used it at all - for me app's icon in the corner is more than enough to identify currently running application, and title destroys overall minimalistic view (especially in browsers, when on some websites title may take up the whole width of panel)

Thanks!

**Comment by Zren** [comment]
While I probably should add a checkbox for this, it's just easier to add another choice in the `TitleAlignment` property.

**Comment by emvaized** [comment]
@Zren 
Awesome! Thanks.
However, for me setting it to 'Hidden' doesn't hide the title, but moves it to the center instead...

![Screenshot_20210316_085514](https://user-images.githubusercontent.com/37851576/111268748-5c4f7800-8636-11eb-9f9f-7b1a624244ca.png)

**Comment by Zren** [comment]
Have you restarted kwin since updating? If you update, the decoration will still have the older version in memory. However if you open the Material config in System Settings, it'll load the config from the new version since it doesn't keep the config window in memory. Since you set a new value that the old version doesn't understand, it used the default `} else {` code path which is `Center` apparently.

**Comment by emvaized** [comment]
@Zren Thanks! I missed that part - now titles are hidden 👍
