### ISSUE TITLE
[applet window buttons] - support kdecoration2 standalone button creation

### ISSUE THREAD

**Issue by psifidotos** [Zren/material-decoration#7]
Currently that theme does not support independent buttons drawing through KDecoration2 so Window Buttons Applet is not drawing anything.
This is achieved through: https://github.com/KDE/breeze/blob/master/kdecoration/breezebutton.h#L48

**Comment by Zren** [comment]
Ah, looks like I gotta move this function to be a static function. `this` can be replaced by casting the unused decoration.

* https://github.com/Zren/material-decoration/blob/lim/src/Decoration.cc#L149

**Comment by Zren** [comment]
How does it know to use `namespace Breeze { static Button::create }`?

I tried moving buttonCreator to a static function (`static Decoration::createButton`), but it doesn't seem to work.

* https://github.com/psifidotos/applet-window-buttons/blob/ef1c332d53926a72bb9ec174345b2f61a770e5c7/libappletdecoration/previewbridge.cpp#L198
* https://github.com/psifidotos/applet-window-buttons/blob/ef1c332d53926a72bb9ec174345b2f61a770e5c7/libappletdecoration/previewbridge.cpp#L161

**Comment by psifidotos** [comment]
I suppose from: https://github.com/KDE/breeze/blob/master/kdecoration/breezedecoration.cpp#L60

**Comment by Zren** [comment]
Thanks, I'm on the right track.

Had to also create a explicit `CommonButton(QObject *parent, const QVariantList &args)` contructor.

* https://github.com/KDE/breeze/blob/master/kdecoration/breezebutton.cpp#L69
* https://github.com/KDE/breeze/blob/master/kdecoration/breezebutton.cpp#L140

Breeze doesn't use `m_flag = FlagStandalone`, but it does use `m_iconSize = QSize(-1, -1)` to set the iconSize to `m_iconSize = geometry().size().toSize()` when painting.

I've managed to get buttons in applet-window-buttons, and the hover effect is visible. I just need to correctly paint the icons.

![2020-04-20___17-44-03](https://user-images.githubusercontent.com/416367/79803565-34756880-8330-11ea-99ae-0c58f4670bd2.png)

**Comment by psifidotos** [comment]
nice!! ;) window buttons everywhere!!! :)
I liked your decoration a lot! Only issue is that in my computer with very high resolution 2560x1440 the window titlebar is really really thin and I can not grow it a bit.

**Comment by Zren** [comment]
Uhg... the reason why there's no icon, is because it's a CommonButton instance. It doesn't use `CommonButton::create()`, it only uses `CommonButton(QObject parent, QVariantList args)`.

So Close/Maximize/Minimize need to have their logic moved out of the descendent classes into `CommonButton` like Breeze. No wonder Breeze only has 1 button class.

`registerPlugin` has a `CreateInstanceFunction` argument, but I've seen no examples I could use.

https://api.kde.org/frameworks/kcoreaddons/html/classKPluginFactory.html#ac6e27887213999995c98716f530f5fcd

**Comment by Zren** [comment]
I've managed to get it working. I'll be moving the fg+bg color logic into CommonButton, then using a switch to call static functions for `init` and `paintIcon` so that buttons are still broken up into different files.

![2020-04-21___16-26-51](https://user-images.githubusercontent.com/416367/79910610-03a73900-83ed-11ea-9201-a9917ded2e00.png)

**Comment by Zren** [comment]
Finished OnAllDesktop and KeepAbove, so the Window Buttons widget should work now.

**Comment by psifidotos** [comment]
Nice!
Really nice to have new implementation for others to follow up. Do you have any idea  how it would be the best way for buttons to provide width/height ratio? I can add it as a user setting in the applet but I would prefer a more automatic way.
